# -*- coding: utf-8 -*-
"""PDSD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/115xIQYfVZIa9Ljc7qCL7GmCnkJj9WQPA
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import zipfile
import os
from google.colab import files
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

# 1. Upload file ZIP
uploaded = files.upload()

# 2. Ekstrak file
for file_name in uploaded.keys():
    if file_name.endswith('.zip'):
        with zipfile.ZipFile(file_name, 'r') as zip_ref:
            zip_ref.extractall('bike_data')
        print(f"✅ Berhasil mengekstrak: {file_name}")

print("Isi folder bike_data:", os.listdir('bike_data'))

# 1. Load Data
df = pd.read_csv('bike_data/day.csv')
df['dteday'] = pd.to_datetime(df['dteday'])

# 2. Pembersihan Outlier dengan Metode IQR (Interquartile Range)
Q1 = df['cnt'].quantile(0.25)
Q3 = df['cnt'].quantile(0.75)
IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

# Filter data
df_clean = df[(df['cnt'] >= lower_limit) & (df['cnt'] <= upper_limit)].copy()

print(f"--- Data Cleaning Selesai ---")
print(f"Baris sebelum: {len(df)}")
print(f"Baris setelah: {len(df_clean)}")
print(f"Jumlah outlier yang dibuang: {len(df) - len(df_clean)}")

# 1. Pilih Fitur & Scaling
features = ['temp', 'hum', 'windspeed', 'cnt']
x = df_clean[features]

scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

# 2. Mencari K Optimal (Elbow Method)
inertia = []
for k in range(1, 11):
    km = KMeans(n_clusters=k, random_state=42, n_init=10)
    km.fit(x_scaled)
    inertia.append(km.inertia_)

plt.figure(figsize=(8, 4))
plt.plot(range(1, 11), inertia, marker='o')
plt.title('Elbow Method untuk Menentukan K')
plt.xlabel('Jumlah Cluster')
plt.ylabel('Inertia')
plt.show()

# 3. Fit Model (Menggunakan K=3 sesuai hasil analisis sebelumnya)
kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
df_clean['cluster'] = kmeans.fit_predict(x_scaled)

# 4. Labeling Otomatis agar Dashboard lebih informatif
# Mengurutkan berdasarkan rata-rata 'cnt' agar Cluster 0 selalu yang tersepi dsb.
means = df_clean.groupby('cluster')['cnt'].mean().sort_values()
mapping = {
    means.index[0]: "Hari Sepi",
    means.index[1]: "Hari Normal",
    means.index[2]: "Hari Ramai"
}
df_clean['cluster_tag'] = df_clean['cluster'].map(mapping)

print("✅ Clustering Selesai dengan 3 Kelompok (Sepi, Normal, Ramai).")

# Simpan file final
final_filename = 'bike_final_model_ready.csv'
df_clean.to_csv(final_filename, index=False)

print(f"File {final_filename} berhasil dibuat.")

# Download file ke komputer lokal
files.download(final_filename)

# Menghitung rata-rata fitur per cluster
profile = data_for_model.groupby('cluster_tag')[['temp', 'hum', 'windspeed', 'cnt']].mean()
print(profile)